/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jid.poc.poc2fa;

import org.jid.poc.poc2fa.wstrange.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
